In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
sys.path.append('/Users/sagarjounkani/Desktop/learning_nlp')

In [3]:
import torch
import torch.nn as nn

In [19]:
from models import RNN, Linear, RNNLayer

In [22]:
rnn = RNN(input_size=2, hidden_size=2, bidirectional=True, num_layers=1)

In [23]:
for p in rnn.parameters():
    print(p)

Parameter containing:
tensor([[ 0.5389, -0.8793],
        [-0.5750,  0.8626]], requires_grad=True)
Parameter containing:
tensor([0.4637, 0.8664], requires_grad=True)
Parameter containing:
tensor([[ 0.8905,  0.2513],
        [ 0.3684, -0.0477]], requires_grad=True)
Parameter containing:
tensor([0.3085, 0.5110], requires_grad=True)
Parameter containing:
tensor([[-1.1515,  1.1609],
        [-0.0445, -0.2042]], requires_grad=True)
Parameter containing:
tensor([0.6193, 0.8059], requires_grad=True)
Parameter containing:
tensor([[0.4989, 1.2136],
        [0.0866, 0.8983]], requires_grad=True)
Parameter containing:
tensor([0.2073, 0.2558], requires_grad=True)
Parameter containing:
tensor([[0., 0.],
        [0., 0.]], requires_grad=True)
Parameter containing:
tensor([[0., 0.],
        [0., 0.]], requires_grad=True)


In [12]:
for p in rnn.layers[0][0].parameters():
    print(p)

Parameter containing:
tensor([[0.0565, 0.1454],
        [0.7545, 0.9465]], requires_grad=True)
Parameter containing:
tensor([0.8409, 0.3955], requires_grad=True)
Parameter containing:
tensor([[ 0.0507,  1.1348],
        [-0.4936,  0.1510]], requires_grad=True)
Parameter containing:
tensor([0.5892, 0.9361], requires_grad=True)


In [17]:
inp1 = torch.ones((1, 2))
inp1

tensor([[1., 1.]])

In [19]:
criterion = nn.NLLLoss()
learning_rate = 0.005 # If you set this too high, it might explode. If too low, it might not learn
optimizer = torch.optim.SGD(rnn.parameters(), lr=learning_rate)

ValueError: optimizer got an empty parameter list

In [33]:
a: nn.ModuleList[nn.ModuleList[Linear]] = nn.ModuleList([nn.ModuleList([Linear(20,2)])])

TypeError: 'type' object is not subscriptable

In [36]:
a: nn.ModuleList[Linear] = nn.ModuleList([Linear(20,2)])

TypeError: 'type' object is not subscriptable

In [35]:
a

ModuleList(
  (0): Linear()
)